builds:
  main: ./build/dsa-go
- env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ignore:
    - goos: freebsd
    - goos: windows
    - goos: linux
    - goos: darwin
changelog:
  use: github

project_name: dsa-go
release:
  github:
    owner: medunes
    name: dsa-go
    # Use a custom tag format that is synchronized with master.
    tag_template: "master-{{ .Commit }}"
