name: tests
on:
  push:
    branches:
      - master
jobs:
  test:
    outputs:
      tests-status: ${{ steps.tests-status.outputs.tests-status }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Test
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set-test-status
        run: |
          # Run your tests here
          # If tests pass, set tests-status to "success", otherwise set it to "failure"
          if go run gotest.tools/gotestsum@latest --format=testdox ./...; then
            echo "tests-status=success" >> $GITHUB_ENV
          else
            echo "tests-status=failure" >> $GITHUB_ENV
          fi